# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainCalculator(object):
    def setupUi(self, MainCalculator):
        MainCalculator.setObjectName("MainCalculator")
        MainCalculator.resize(800, 717)
        MainCalculator.setMaximumSize(QtCore.QSize(800, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_header.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #0954B2;")
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_header)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_title = QtWidgets.QLabel(self.frame_header)
        self.lb_title.setObjectName("lb_title")
        self.verticalLayout_2.addWidget(self.lb_title)
        self.verticalLayout.addWidget(self.frame_header)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_investment = QtWidgets.QFrame(self.frame_2)
        self.frame_investment.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_investment.setSizeIncrement(QtCore.QSize(0, 300))
        self.frame_investment.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_investment.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_investment.setObjectName("frame_investment")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_investment)
        self.gridLayout.setContentsMargins(70, 15, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_profit = QtWidgets.QLabel(self.frame_investment)
        self.lb_profit.setMinimumSize(QtCore.QSize(100, 0))
        self.lb_profit.setStyleSheet("background-color: #0954B2;")
        self.lb_profit.setObjectName("lb_profit")
        self.gridLayout.addWidget(self.lb_profit, 1, 1, 1, 1)
        self.le_profit = QtWidgets.QLineEdit(self.frame_investment)
        self.le_profit.setMinimumSize(QtCore.QSize(200, 50))
        self.le_profit.setMaximumSize(QtCore.QSize(80, 50))
        self.le_profit.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_profit.setReadOnly(True)
        self.le_profit.setObjectName("le_profit")
        self.gridLayout.addWidget(self.le_profit, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(463, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        self.le_tot_return = QtWidgets.QLineEdit(self.frame_investment)
        self.le_tot_return.setMinimumSize(QtCore.QSize(200, 50))
        self.le_tot_return.setMaximumSize(QtCore.QSize(80, 50))
        self.le_tot_return.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_tot_return.setReadOnly(True)
        self.le_tot_return.setObjectName("le_tot_return")
        self.gridLayout.addWidget(self.le_tot_return, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(463, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(463, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 5, 1, 1)
        self.le_value_invest = QtWidgets.QLineEdit(self.frame_investment)
        self.le_value_invest.setMinimumSize(QtCore.QSize(200, 50))
        self.le_value_invest.setMaximumSize(QtCore.QSize(80, 16777215))
        self.le_value_invest.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_value_invest.setObjectName("le_value_invest")
        self.gridLayout.addWidget(self.le_value_invest, 0, 4, 1, 1)
        self.lb_tot_return = QtWidgets.QLabel(self.frame_investment)
        self.lb_tot_return.setMinimumSize(QtCore.QSize(100, 0))
        self.lb_tot_return.setStyleSheet("background-color: #0954B2;")
        self.lb_tot_return.setObjectName("lb_tot_return")
        self.gridLayout.addWidget(self.lb_tot_return, 2, 1, 1, 1)
        self.lb_investment = QtWidgets.QLabel(self.frame_investment)
        self.lb_investment.setMinimumSize(QtCore.QSize(150, 0))
        self.lb_investment.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lb_investment.setStyleSheet("background-color: #0954B2;")
        self.lb_investment.setObjectName("lb_investment")
        self.gridLayout.addWidget(self.lb_investment, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_investment)
        self.fram_odds = QtWidgets.QFrame(self.frame_2)
        self.fram_odds.setMaximumSize(QtCore.QSize(800, 16777215))
        self.fram_odds.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fram_odds.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fram_odds.setObjectName("fram_odds")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fram_odds)
        self.gridLayout_2.setContentsMargins(0, 25, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 4, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 4, 0, 1, 1)
        self.le_return2 = QtWidgets.QLineEdit(self.fram_odds)
        self.le_return2.setMinimumSize(QtCore.QSize(200, 50))
        self.le_return2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_return2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_return2.setAlignment(QtCore.Qt.AlignCenter)
        self.le_return2.setDragEnabled(False)
        self.le_return2.setReadOnly(True)
        self.le_return2.setObjectName("le_return2")
        self.gridLayout_2.addWidget(self.le_return2, 2, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        self.lb_odds2 = QtWidgets.QLabel(self.fram_odds)
        self.lb_odds2.setMinimumSize(QtCore.QSize(100, 50))
        self.lb_odds2.setMaximumSize(QtCore.QSize(100, 50))
        self.lb_odds2.setStyleSheet("background-color: #0954B2;")
        self.lb_odds2.setObjectName("lb_odds2")
        self.gridLayout_2.addWidget(self.lb_odds2, 1, 1, 1, 1)
        self.lb_parcial_investment = QtWidgets.QLabel(self.fram_odds)
        self.lb_parcial_investment.setMinimumSize(QtCore.QSize(0, 50))
        self.lb_parcial_investment.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lb_parcial_investment.setStyleSheet("background-color: #0954B2;")
        self.lb_parcial_investment.setObjectName("lb_parcial_investment")
        self.gridLayout_2.addWidget(self.lb_parcial_investment, 0, 3, 1, 1)
        self.lb_parcial_return = QtWidgets.QLabel(self.fram_odds)
        self.lb_parcial_return.setMinimumSize(QtCore.QSize(0, 50))
        self.lb_parcial_return.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lb_parcial_return.setStyleSheet("background-color: #0954B2;")
        self.lb_parcial_return.setObjectName("lb_parcial_return")
        self.gridLayout_2.addWidget(self.lb_parcial_return, 0, 5, 1, 1)
        self.le_odds1 = QtWidgets.QLineEdit(self.fram_odds)
        self.le_odds1.setMinimumSize(QtCore.QSize(0, 50))
        self.le_odds1.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_odds1.setAlignment(QtCore.Qt.AlignCenter)
        self.le_odds1.setDragEnabled(False)
        self.le_odds1.setReadOnly(False)
        self.le_odds1.setObjectName("le_odds1")
        self.gridLayout_2.addWidget(self.le_odds1, 1, 2, 1, 1)
        self.le_invest1 = QtWidgets.QLineEdit(self.fram_odds)
        self.le_invest1.setMinimumSize(QtCore.QSize(200, 50))
        self.le_invest1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_invest1.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_invest1.setAlignment(QtCore.Qt.AlignCenter)
        self.le_invest1.setDragEnabled(False)
        self.le_invest1.setReadOnly(True)
        self.le_invest1.setObjectName("le_invest1")
        self.gridLayout_2.addWidget(self.le_invest1, 1, 3, 1, 1)
        self.le_odds2 = QtWidgets.QLineEdit(self.fram_odds)
        self.le_odds2.setMinimumSize(QtCore.QSize(0, 50))
        self.le_odds2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_odds2.setAlignment(QtCore.Qt.AlignCenter)
        self.le_odds2.setDragEnabled(False)
        self.le_odds2.setReadOnly(False)
        self.le_odds2.setObjectName("le_odds2")
        self.gridLayout_2.addWidget(self.le_odds2, 2, 2, 1, 1)
        self.le_return1 = QtWidgets.QLineEdit(self.fram_odds)
        self.le_return1.setMinimumSize(QtCore.QSize(200, 50))
        self.le_return1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_return1.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_return1.setAlignment(QtCore.Qt.AlignCenter)
        self.le_return1.setDragEnabled(False)
        self.le_return1.setReadOnly(True)
        self.le_return1.setObjectName("le_return1")
        self.gridLayout_2.addWidget(self.le_return1, 1, 4, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(43, 27, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 2, 0, 1, 1)
        self.lb_odds1 = QtWidgets.QLabel(self.fram_odds)
        self.lb_odds1.setMinimumSize(QtCore.QSize(100, 50))
        self.lb_odds1.setMaximumSize(QtCore.QSize(100, 50))
        self.lb_odds1.setStyleSheet("background-color: #0954B2;")
        self.lb_odds1.setObjectName("lb_odds1")
        self.gridLayout_2.addWidget(self.lb_odds1, 2, 1, 1, 1)
        self.le_invest2 = QtWidgets.QLineEdit(self.fram_odds)
        self.le_invest2.setMinimumSize(QtCore.QSize(200, 50))
        self.le_invest2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_invest2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(231, 231, 231);")
        self.le_invest2.setAlignment(QtCore.Qt.AlignCenter)
        self.le_invest2.setDragEnabled(False)
        self.le_invest2.setReadOnly(True)
        self.le_invest2.setObjectName("le_invest2")
        self.gridLayout_2.addWidget(self.le_invest2, 2, 3, 1, 2)
        self.btn_calc = QtWidgets.QPushButton(self.fram_odds)
        self.btn_calc.setMinimumSize(QtCore.QSize(200, 100))
        self.btn_calc.setMaximumSize(QtCore.QSize(170, 100))
        self.btn_calc.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 8px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(26, 60, 102);\n"
"    border-radius: 8px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#0954B2;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_calc.setObjectName("btn_calc")
        self.gridLayout_2.addWidget(self.btn_calc, 3, 3, 1, 1)
        self.btn_back = QtWidgets.QPushButton(self.fram_odds)
        self.btn_back.setMinimumSize(QtCore.QSize(200, 45))
        self.btn_back.setMaximumSize(QtCore.QSize(200, 45))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 8px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(26, 60, 102);\n"
"    border-radius: 8px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#0954B2;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_back.setObjectName("btn_back")
        self.gridLayout_2.addWidget(self.btn_back, 4, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.fram_odds)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_footer = QtWidgets.QFrame(self.centralwidget)
        self.frame_footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_footer.setStyleSheet("background-color: #0954B2;\n"
"border-radius: 2px;\n"
"")
        self.frame_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer.setObjectName("frame_footer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_footer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_commom = QtWidgets.QLabel(self.frame_footer)
        self.lb_commom.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"")
        self.lb_commom.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_commom.setObjectName("lb_commom")
        self.verticalLayout_3.addWidget(self.lb_commom)
        self.verticalLayout.addWidget(self.frame_footer)
        MainCalculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainCalculator)
        QtCore.QMetaObject.connectSlotsByName(MainCalculator)

    def retranslateUi(self, MainCalculator):
        _translate = QtCore.QCoreApplication.translate
        MainCalculator.setWindowTitle(_translate("MainCalculator", "MainWindow"))
        self.lb_title.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Calcular Aposta</span></p></body></html>"))
        self.lb_profit.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Lucro</span></p></body></html>"))
        self.le_profit.setPlaceholderText(_translate("MainCalculator", "R$"))
        self.le_tot_return.setPlaceholderText(_translate("MainCalculator", "R$"))
        self.le_value_invest.setPlaceholderText(_translate("MainCalculator", "R$"))
        self.lb_tot_return.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Retorno</span></p></body></html>"))
        self.lb_investment.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Investimento</span></p></body></html>"))
        self.le_return2.setPlaceholderText(_translate("MainCalculator", "Odds"))
        self.lb_odds2.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Odds1</span></p></body></html>"))
        self.lb_parcial_investment.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Investimento</span></p></body></html>"))
        self.lb_parcial_return.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Retorno</span></p></body></html>"))
        self.le_odds1.setPlaceholderText(_translate("MainCalculator", "Odds"))
        self.le_invest1.setPlaceholderText(_translate("MainCalculator", "Odds"))
        self.le_odds2.setPlaceholderText(_translate("MainCalculator", "Odds"))
        self.le_return1.setPlaceholderText(_translate("MainCalculator", "Odds"))
        self.lb_odds1.setText(_translate("MainCalculator", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Odds2</span></p></body></html>"))
        self.le_invest2.setPlaceholderText(_translate("MainCalculator", "Odds"))
        self.btn_calc.setText(_translate("MainCalculator", "Calcular"))
        self.btn_back.setText(_translate("MainCalculator", "Voltar"))
        self.lb_commom.setText(_translate("MainCalculator", "Todos os direitos reservados ©  MaTTecnologia Aplicada 2022"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainCalculator = QtWidgets.QMainWindow()
    ui = Ui_MainCalculator()
    ui.setupUi(MainCalculator)
    MainCalculator.show()
    sys.exit(app.exec_())
