# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.setWindowModality(QtCore.Qt.ApplicationModal)
        Main.resize(1136, 685)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/main_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        Main.setIconSize(QtCore.QSize(70, 70))
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top.setStyleSheet("background-color: #0954B2;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_btn_menu = QtWidgets.QFrame(self.frame_top)
        self.frame_btn_menu.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_btn_menu.setMaximumSize(QtCore.QSize(100, 60))
        self.frame_btn_menu.setStyleSheet("background-color:#0954B2;")
        self.frame_btn_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_menu.setObjectName("frame_btn_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_btn_menu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_menu = QtWidgets.QPushButton(self.frame_btn_menu)
        self.btn_menu.setMinimumSize(QtCore.QSize(100, 80))
        self.btn_menu.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_menu.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 25px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#0954B2;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/menu_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon1)
        self.btn_menu.setIconSize(QtCore.QSize(32, 32))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_4.addWidget(self.btn_menu)
        self.horizontalLayout_2.addWidget(self.frame_btn_menu)
        self.frame_info = QtWidgets.QFrame(self.frame_top)
        self.frame_info.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_info.setStyleSheet("background-color: rgb(9, 84, 178);")
        self.frame_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2.addWidget(self.frame_info)
        self.verticalLayout_10.addWidget(self.frame_top)
        self.fram_bot = QtWidgets.QFrame(self.centralwidget)
        self.fram_bot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fram_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fram_bot.setObjectName("fram_bot")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fram_bot)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_side = QtWidgets.QFrame(self.fram_bot)
        self.frame_side.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_side.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_side.setStyleSheet("background-color: #FFF;\n"
"border: 2px solid;\n"
"border-left: none;\n"
"border-top: none;\n"
"border-bottom:none;\n"
"border-right-color: #0954B2;")
        self.frame_side.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_side.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_side.setObjectName("frame_side")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_side)
        self.verticalLayout.setContentsMargins(0, 35, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_coletar = QtWidgets.QPushButton(self.frame_side)
        self.btn_coletar.setMinimumSize(QtCore.QSize(200, 45))
        self.btn_coletar.setMaximumSize(QtCore.QSize(200, 45))
        self.btn_coletar.setBaseSize(QtCore.QSize(0, 0))
        self.btn_coletar.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_coletar.setText("Coletar Odds")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../src/collect_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_coletar.setIcon(icon2)
        self.btn_coletar.setIconSize(QtCore.QSize(45, 40))
        self.btn_coletar.setObjectName("btn_coletar")
        self.verticalLayout.addWidget(self.btn_coletar, 0, QtCore.Qt.AlignHCenter)
        self.btn_visJogos = QtWidgets.QPushButton(self.frame_side)
        self.btn_visJogos.setMinimumSize(QtCore.QSize(200, 45))
        self.btn_visJogos.setMaximumSize(QtCore.QSize(200, 45))
        self.btn_visJogos.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../src/games_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_visJogos.setIcon(icon3)
        self.btn_visJogos.setIconSize(QtCore.QSize(45, 40))
        self.btn_visJogos.setObjectName("btn_visJogos")
        self.verticalLayout.addWidget(self.btn_visJogos, 0, QtCore.Qt.AlignHCenter)
        self.btn_visProbabilidades = QtWidgets.QPushButton(self.frame_side)
        self.btn_visProbabilidades.setMinimumSize(QtCore.QSize(200, 45))
        self.btn_visProbabilidades.setMaximumSize(QtCore.QSize(200, 45))
        self.btn_visProbabilidades.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../src/possibility_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_visProbabilidades.setIcon(icon4)
        self.btn_visProbabilidades.setIconSize(QtCore.QSize(45, 40))
        self.btn_visProbabilidades.setObjectName("btn_visProbabilidades")
        self.verticalLayout.addWidget(self.btn_visProbabilidades, 0, QtCore.Qt.AlignHCenter)
        self.btn_previsoes = QtWidgets.QPushButton(self.frame_side)
        self.btn_previsoes.setMinimumSize(QtCore.QSize(200, 45))
        self.btn_previsoes.setMaximumSize(QtCore.QSize(200, 45))
        self.btn_previsoes.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../src/odds_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_previsoes.setIcon(icon5)
        self.btn_previsoes.setIconSize(QtCore.QSize(45, 40))
        self.btn_previsoes.setObjectName("btn_previsoes")
        self.verticalLayout.addWidget(self.btn_previsoes, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 383, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_about = QtWidgets.QFrame(self.frame_side)
        self.frame_about.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_about.setStyleSheet("background-color: rgb(9, 84, 178);")
        self.frame_about.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_about.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about.setObjectName("frame_about")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_about)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_about = QtWidgets.QPushButton(self.frame_about)
        self.btn_about.setMinimumSize(QtCore.QSize(225, 35))
        self.btn_about.setMaximumSize(QtCore.QSize(230, 35))
        self.btn_about.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #4195FF;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("src/about_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_about.setIcon(icon6)
        self.btn_about.setIconSize(QtCore.QSize(25, 25))
        self.btn_about.setAutoDefault(True)
        self.btn_about.setDefault(False)
        self.btn_about.setFlat(False)
        self.btn_about.setObjectName("btn_about")
        self.verticalLayout_2.addWidget(self.btn_about, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_about, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_side)
        self.frame_content = QtWidgets.QFrame(self.fram_bot)
        self.frame_content.setStyleSheet("background-color:#0954B2;")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_pages = QtWidgets.QFrame(self.frame_content)
        self.frame_pages.setStyleSheet("background-color: #fff;")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_pages)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pages = QtWidgets.QStackedWidget(self.frame_pages)
        self.pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pages.setAutoFillBackground(False)
        self.pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pages.setLineWidth(0)
        self.pages.setObjectName("pages")
        self.page_view_games = QtWidgets.QWidget()
        self.page_view_games.setObjectName("page_view_games")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_view_games)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_options_games = QtWidgets.QFrame(self.page_view_games)
        self.frame_options_games.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_options_games.setStyleSheet("background-color: #4195FF;")
        self.frame_options_games.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_options_games.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_options_games.setObjectName("frame_options_games")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_options_games)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rb_jogos_betano = QtWidgets.QRadioButton(self.frame_options_games)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_jogos_betano.sizePolicy().hasHeightForWidth())
        self.rb_jogos_betano.setSizePolicy(sizePolicy)
        self.rb_jogos_betano.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_jogos_betano.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_jogos_betano.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_jogos_betano.setAutoRepeatDelay(300)
        self.rb_jogos_betano.setAutoRepeatInterval(100)
        self.rb_jogos_betano.setObjectName("rb_jogos_betano")
        self.horizontalLayout_10.addWidget(self.rb_jogos_betano)
        self.rb_jogos_pixbet = QtWidgets.QRadioButton(self.frame_options_games)
        self.rb_jogos_pixbet.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_jogos_pixbet.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_jogos_pixbet.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_jogos_pixbet.setObjectName("rb_jogos_pixbet")
        self.horizontalLayout_10.addWidget(self.rb_jogos_pixbet)
        self.verticalLayout_11.addWidget(self.frame_options_games)
        self.frame_tb_games = QtWidgets.QFrame(self.page_view_games)
        self.frame_tb_games.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tb_games.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tb_games.setObjectName("frame_tb_games")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_tb_games)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tb_view_games = QtWidgets.QTableWidget(self.frame_tb_games)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tb_view_games.setFont(font)
        self.tb_view_games.setToolTipDuration(-3)
        self.tb_view_games.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(243, 243, 243);\n"
"")
        self.tb_view_games.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tb_view_games.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tb_view_games.setAutoScrollMargin(20)
        self.tb_view_games.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_view_games.setDragEnabled(False)
        self.tb_view_games.setAlternatingRowColors(True)
        self.tb_view_games.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tb_view_games.setIconSize(QtCore.QSize(0, 0))
        self.tb_view_games.setTextElideMode(QtCore.Qt.ElideRight)
        self.tb_view_games.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_view_games.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_view_games.setColumnCount(15)
        self.tb_view_games.setObjectName("tb_view_games")
        self.tb_view_games.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../src/order_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view_games.setHorizontalHeaderItem(14, item)
        self.tb_view_games.horizontalHeader().setDefaultSectionSize(150)
        self.tb_view_games.horizontalHeader().setMinimumSectionSize(50)
        self.tb_view_games.verticalHeader().setVisible(False)
        self.tb_view_games.verticalHeader().setDefaultSectionSize(50)
        self.tb_view_games.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_14.addWidget(self.tb_view_games)
        self.verticalLayout_11.addWidget(self.frame_tb_games)
        self.pages.addWidget(self.page_view_games)
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_home)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.page_home)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lb_collect_animation = QtWidgets.QLabel(self.frame_2)
        self.lb_collect_animation.setText("")
        self.lb_collect_animation.setPixmap(QtGui.QPixmap("src/texte_icon.gif"))
        self.lb_collect_animation.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_collect_animation.setObjectName("lb_collect_animation")
        self.verticalLayout_8.addWidget(self.lb_collect_animation)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.page_home)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_text_animation = QtWidgets.QLabel(self.frame_4)
        self.lb_text_animation.setMinimumSize(QtCore.QSize(0, 0))
        self.lb_text_animation.setText("")
        self.lb_text_animation.setPixmap(QtGui.QPixmap("src/texte_icon.gif"))
        self.lb_text_animation.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_text_animation.setObjectName("lb_text_animation")
        self.verticalLayout_7.addWidget(self.lb_text_animation)
        self.gridLayout_2.addWidget(self.frame_4, 1, 0, 1, 1)
        self.pages.addWidget(self.page_home)
        self.page_preview = QtWidgets.QWidget()
        self.page_preview.setObjectName("page_preview")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_preview)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_options_camp = QtWidgets.QFrame(self.page_preview)
        self.frame_options_camp.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_options_camp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_options_camp.setStyleSheet("background-color: #4195FF;")
        self.frame_options_camp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_options_camp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_options_camp.setObjectName("frame_options_camp")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_options_camp)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_options_camp)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.cb_camp = QtWidgets.QComboBox(self.frame_3)
        self.cb_camp.setMinimumSize(QtCore.QSize(0, 40))
        self.cb_camp.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_camp.setFont(font)
        self.cb_camp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_camp.setIconSize(QtCore.QSize(16, 16))
        self.cb_camp.setObjectName("cb_camp")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../src/list_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.cb_camp.addItem(icon8, "")
        self.verticalLayout_13.addWidget(self.cb_camp)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame_options_camp)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_season = QtWidgets.QFrame(self.frame_5)
        self.frame_season.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_season.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_season.setObjectName("frame_season")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_season)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rb_games_future = QtWidgets.QRadioButton(self.frame_season)
        self.rb_games_future.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_games_future.setObjectName("rb_games_future")
        self.horizontalLayout_11.addWidget(self.rb_games_future)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.rb_games_past = QtWidgets.QRadioButton(self.frame_season)
        self.rb_games_past.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_games_past.setObjectName("rb_games_past")
        self.horizontalLayout_11.addWidget(self.rb_games_past)
        spacerItem2 = QtWidgets.QSpacerItem(463, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_16.addWidget(self.frame_season)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.le_team1 = QtWidgets.QLineEdit(self.frame_6)
        self.le_team1.setMinimumSize(QtCore.QSize(200, 40))
        self.le_team1.setMaximumSize(QtCore.QSize(200, 40))
        self.le_team1.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.le_team1.setObjectName("le_team1")
        self.horizontalLayout_9.addWidget(self.le_team1, 0, QtCore.Qt.AlignBottom)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.le_team2 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_team2.sizePolicy().hasHeightForWidth())
        self.le_team2.setSizePolicy(sizePolicy)
        self.le_team2.setMinimumSize(QtCore.QSize(200, 40))
        self.le_team2.setMaximumSize(QtCore.QSize(200, 40))
        self.le_team2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.le_team2.setObjectName("le_team2")
        self.horizontalLayout_9.addWidget(self.le_team2, 0, QtCore.Qt.AlignBottom)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.btn_search = QtWidgets.QPushButton(self.frame_6)
        self.btn_search.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_search.setMaximumSize(QtCore.QSize(150, 35))
        self.btn_search.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_search.setFont(font)
        self.btn_search.setWhatsThis("")
        self.btn_search.setAccessibleDescription("")
        self.btn_search.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0954B2;\n"
"    border-radius: 8px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(26, 60, 102);\n"
"    border-radius: 8px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#0954B2;\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../src/search_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon9)
        self.btn_search.setIconSize(QtCore.QSize(35, 35))
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_9.addWidget(self.btn_search)
        spacerItem5 = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.verticalLayout_9.addWidget(self.frame_options_camp)
        self.frame_preview = QtWidgets.QFrame(self.page_preview)
        self.frame_preview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_preview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preview.setObjectName("frame_preview")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_preview)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tb_preview = QtWidgets.QTableWidget(self.frame_preview)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tb_preview.setFont(font)
        self.tb_preview.setToolTipDuration(-3)
        self.tb_preview.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(243, 243, 243);\n"
"")
        self.tb_preview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tb_preview.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tb_preview.setAutoScrollMargin(20)
        self.tb_preview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_preview.setDragEnabled(False)
        self.tb_preview.setAlternatingRowColors(True)
        self.tb_preview.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tb_preview.setIconSize(QtCore.QSize(0, 0))
        self.tb_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.tb_preview.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_preview.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_preview.setColumnCount(15)
        self.tb_preview.setObjectName("tb_preview")
        self.tb_preview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_preview.setHorizontalHeaderItem(14, item)
        self.tb_preview.horizontalHeader().setDefaultSectionSize(150)
        self.tb_preview.horizontalHeader().setMinimumSectionSize(50)
        self.tb_preview.verticalHeader().setVisible(False)
        self.tb_preview.verticalHeader().setDefaultSectionSize(50)
        self.tb_preview.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_12.addWidget(self.tb_preview)
        self.verticalLayout_9.addWidget(self.frame_preview)
        self.pages.addWidget(self.page_preview)
        self.page_possibilities = QtWidgets.QWidget()
        self.page_possibilities.setMouseTracking(False)
        self.page_possibilities.setTabletTracking(False)
        self.page_possibilities.setObjectName("page_possibilities")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_possibilities)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.page_possibilities)
        self.frame.setStyleSheet("background-color: #4195FF;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_options = QtWidgets.QFrame(self.frame)
        self.frame_options.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_options.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_options.setStyleSheet("background-color: #4195FF;")
        self.frame_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_options.setLineWidth(1)
        self.frame_options.setObjectName("frame_options")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_options)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rb_DuplaChance = QtWidgets.QRadioButton(self.frame_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_DuplaChance.sizePolicy().hasHeightForWidth())
        self.rb_DuplaChance.setSizePolicy(sizePolicy)
        self.rb_DuplaChance.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_DuplaChance.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_DuplaChance.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_DuplaChance.setAutoRepeatDelay(300)
        self.rb_DuplaChance.setAutoRepeatInterval(100)
        self.rb_DuplaChance.setObjectName("rb_DuplaChance")
        self.horizontalLayout_6.addWidget(self.rb_DuplaChance)
        self.rb_matchOdds = QtWidgets.QRadioButton(self.frame_options)
        self.rb_matchOdds.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_matchOdds.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_matchOdds.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_matchOdds.setObjectName("rb_matchOdds")
        self.horizontalLayout_6.addWidget(self.rb_matchOdds)
        self.rb_ambosMarcam = QtWidgets.QRadioButton(self.frame_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_ambosMarcam.sizePolicy().hasHeightForWidth())
        self.rb_ambosMarcam.setSizePolicy(sizePolicy)
        self.rb_ambosMarcam.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_ambosMarcam.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_ambosMarcam.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_ambosMarcam.setObjectName("rb_ambosMarcam")
        self.horizontalLayout_6.addWidget(self.rb_ambosMarcam)
        self.rb_totalGols = QtWidgets.QRadioButton(self.frame_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_totalGols.sizePolicy().hasHeightForWidth())
        self.rb_totalGols.setSizePolicy(sizePolicy)
        self.rb_totalGols.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_totalGols.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_totalGols.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_totalGols.setChecked(True)
        self.rb_totalGols.setAutoRepeat(True)
        self.rb_totalGols.setObjectName("rb_totalGols")
        self.horizontalLayout_6.addWidget(self.rb_totalGols)
        self.verticalLayout_5.addWidget(self.frame_options)
        self.frame_tb = QtWidgets.QFrame(self.frame)
        self.frame_tb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tb.setObjectName("frame_tb")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_tb)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tb_view = QtWidgets.QTableWidget(self.frame_tb)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tb_view.setFont(font)
        self.tb_view.setToolTipDuration(-3)
        self.tb_view.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(243, 243, 243);\n"
"")
        self.tb_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tb_view.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tb_view.setAutoScrollMargin(20)
        self.tb_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_view.setDragEnabled(False)
        self.tb_view.setAlternatingRowColors(True)
        self.tb_view.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tb_view.setIconSize(QtCore.QSize(0, 0))
        self.tb_view.setTextElideMode(QtCore.Qt.ElideRight)
        self.tb_view.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_view.setColumnCount(15)
        self.tb_view.setObjectName("tb_view")
        self.tb_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon7)
        self.tb_view.setHorizontalHeaderItem(14, item)
        self.tb_view.horizontalHeader().setDefaultSectionSize(150)
        self.tb_view.horizontalHeader().setMinimumSectionSize(50)
        self.tb_view.verticalHeader().setVisible(False)
        self.tb_view.verticalHeader().setDefaultSectionSize(50)
        self.tb_view.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_6.addWidget(self.tb_view)
        self.verticalLayout_5.addWidget(self.frame_tb)
        self.horizontalLayout_5.addWidget(self.frame)
        self.pages.addWidget(self.page_possibilities)
        self.horizontalLayout_3.addWidget(self.pages)
        self.verticalLayout_3.addWidget(self.frame_pages)
        self.frame_commom = QtWidgets.QFrame(self.frame_content)
        self.frame_commom.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_commom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_commom.setStyleSheet("background-color: #0954B2;\n"
"border-radius: 2px;\n"
"")
        self.frame_commom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_commom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_commom.setObjectName("frame_commom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_commom)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lb_commom = QtWidgets.QLabel(self.frame_commom)
        self.lb_commom.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"")
        self.lb_commom.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_commom.setObjectName("lb_commom")
        self.verticalLayout_4.addWidget(self.lb_commom)
        self.verticalLayout_3.addWidget(self.frame_commom)
        self.horizontalLayout.addWidget(self.frame_content)
        self.verticalLayout_10.addWidget(self.fram_bot)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        self.pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Modulo Principal"))
        self.btn_menu.setText(_translate("Main", "Menu"))
        self.btn_visJogos.setText(_translate("Main", "Visualizar Jogos"))
        self.btn_visProbabilidades.setText(_translate("Main", "Possibilidaes"))
        self.btn_previsoes.setText(_translate("Main", "Previsões"))
        self.btn_about.setText(_translate("Main", "Sobre"))
        self.rb_jogos_betano.setText(_translate("Main", "Jogos Betano"))
        self.rb_jogos_pixbet.setText(_translate("Main", "Jogos Pixbet"))
        self.tb_view_games.setSortingEnabled(True)
        item = self.tb_view_games.horizontalHeaderItem(0)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(1)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(2)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(3)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(4)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(5)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(6)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(7)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(8)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(9)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(10)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(11)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(12)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(13)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view_games.horizontalHeaderItem(14)
        item.setText(_translate("Main", "New Column"))
        self.label.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Campeonato</span></p></body></html>"))
        self.cb_camp.setItemText(0, _translate("Main", "Argentina Primera Division"))
        self.cb_camp.setItemText(1, _translate("Main", "Australian A-League"))
        self.cb_camp.setItemText(2, _translate("Main", "Austrian T-Mobile Bundesliga"))
        self.cb_camp.setItemText(3, _translate("Main", "Barclays Premier League"))
        self.cb_camp.setItemText(4, _translate("Main", "Belgian Jupiler League"))
        self.cb_camp.setItemText(5, _translate("Main", "Brasileiro Série A"))
        self.cb_camp.setItemText(6, _translate("Main", "Chinese Super League"))
        self.cb_camp.setItemText(7, _translate("Main", "Danish SAS-Ligaen"))
        self.cb_camp.setItemText(8, _translate("Main", "Dutch Eredivisie"))
        self.cb_camp.setItemText(9, _translate("Main", "English League Championship"))
        self.cb_camp.setItemText(10, _translate("Main", "English League One"))
        self.cb_camp.setItemText(11, _translate("Main", "English League Two"))
        self.cb_camp.setItemText(12, _translate("Main", "FA Women\'s Super League"))
        self.cb_camp.setItemText(13, _translate("Main", "French Ligue 1"))
        self.cb_camp.setItemText(14, _translate("Main", "French Ligue 2"))
        self.cb_camp.setItemText(15, _translate("Main", "German 2. Bundesliga"))
        self.cb_camp.setItemText(16, _translate("Main", "German Bundesliga"))
        self.cb_camp.setItemText(17, _translate("Main", "Greek Super League"))
        self.cb_camp.setItemText(18, _translate("Main", "Italy Serie A"))
        self.cb_camp.setItemText(19, _translate("Main", "Italy Serie B"))
        self.cb_camp.setItemText(20, _translate("Main", "Japanese J League"))
        self.cb_camp.setItemText(21, _translate("Main", "Major League Soccer"))
        self.cb_camp.setItemText(22, _translate("Main", "Mexican Primera Division Torneo Apertura"))
        self.cb_camp.setItemText(23, _translate("Main", "Mexican Primera Division Torneo Clausura"))
        self.cb_camp.setItemText(24, _translate("Main", "NWSL Challenge Cup"))
        self.cb_camp.setItemText(25, _translate("Main", "National Women\'s Soccer League"))
        self.cb_camp.setItemText(26, _translate("Main", "Norwegian Tippeligaen"))
        self.cb_camp.setItemText(27, _translate("Main", "Portuguese Liga"))
        self.cb_camp.setItemText(28, _translate("Main", "Russian Premier Liga"))
        self.cb_camp.setItemText(29, _translate("Main", "Scottish Premiership"))
        self.cb_camp.setItemText(30, _translate("Main", "South African ABSA Premier League"))
        self.cb_camp.setItemText(31, _translate("Main", "Spanish Primera Division"))
        self.cb_camp.setItemText(32, _translate("Main", "Spanish Segunda Division"))
        self.cb_camp.setItemText(33, _translate("Main", "Swedish Allsvenskan"))
        self.cb_camp.setItemText(34, _translate("Main", "Swiss Raiffeisen Super League"))
        self.cb_camp.setItemText(35, _translate("Main", "Turkish Turkcell Super Lig"))
        self.cb_camp.setItemText(36, _translate("Main", "UEFA Champions League"))
        self.cb_camp.setItemText(37, _translate("Main", "UEFA Europa Conference League"))
        self.cb_camp.setItemText(38, _translate("Main", "UEFA Europa League"))
        self.cb_camp.setItemText(39, _translate("Main", "United Soccer League"))
        self.rb_games_future.setText(_translate("Main", "Jogos Futuros"))
        self.rb_games_past.setText(_translate("Main", "Jogos Passados"))
        self.le_team1.setPlaceholderText(_translate("Main", "Mandante"))
        self.le_team2.setPlaceholderText(_translate("Main", "Visitante"))
        self.btn_search.setText(_translate("Main", "Pesquisar"))
        self.tb_preview.setSortingEnabled(True)
        item = self.tb_preview.horizontalHeaderItem(0)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(1)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(2)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(3)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(4)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(5)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(6)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(7)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(8)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(9)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(10)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(11)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(12)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(13)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_preview.horizontalHeaderItem(14)
        item.setText(_translate("Main", "New Column"))
        self.rb_DuplaChance.setText(_translate("Main", "Dupla Chance"))
        self.rb_matchOdds.setText(_translate("Main", "Match Odds"))
        self.rb_ambosMarcam.setText(_translate("Main", "Ambos Marcam"))
        self.rb_totalGols.setText(_translate("Main", "Total de Gols"))
        self.tb_view.setSortingEnabled(True)
        item = self.tb_view.horizontalHeaderItem(0)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(1)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(2)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(3)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(4)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(5)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(6)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(7)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(8)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(9)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(10)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(11)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(12)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(13)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(14)
        item.setText(_translate("Main", "New Column"))
        self.lb_commom.setText(_translate("Main", "Todos os direitos reservados ©  MaTTecnologia Aplicada 2022"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
