# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'install.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formInstall(object):
    def setupUi(self, formInstall):
        formInstall.setObjectName("formInstall")
        formInstall.resize(620, 250)
        formInstall.setMaximumSize(QtCore.QSize(620, 250))
        formInstall.setFocusPolicy(QtCore.Qt.ClickFocus)
        formInstall.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(formInstall)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(0, 0, 601, 111))
        self.lbl_title.setObjectName("lbl_title")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(100, 160, 195, 45))
        self.btn_start.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(3, 127, 140);")
        self.btn_start.setObjectName("btn_start")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(300, 160, 195, 45))
        self.btn_exit.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(3, 127, 140);")
        self.btn_exit.setObjectName("btn_exit")
        self.br_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.br_progress.setEnabled(True)
        self.br_progress.setGeometry(QtCore.QRect(40, 120, 561, 23))
        self.br_progress.setProperty("value", 0)
        self.br_progress.setTextVisible(True)
        self.br_progress.setObjectName("br_progress")
        formInstall.setCentralWidget(self.centralwidget)

        self.retranslateUi(formInstall)
        QtCore.QMetaObject.connectSlotsByName(formInstall)
        
        ### Botão iniciar ###
        self.btn_start.clicked.connect()

    def retranslateUi(self, formInstall):
        _translate = QtCore.QCoreApplication.translate
        formInstall.setWindowTitle(_translate("formInstall", "Assitente de Instalação"))
        self.lbl_title.setText(_translate("formInstall", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#037f8c;\">BEM VINDO AO ASSISTENTE DE INSTALAÇÃO - GAE</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#037f8c;\">GERENCIADOR DE APOSTAS ESPORTIVAS</span></p></body></html>"))
        self.btn_start.setText(_translate("formInstall", "Iniciar instalação"))
        self.btn_exit.setText(_translate("formInstall", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formInstall = QtWidgets.QMainWindow()
    ui = Ui_formInstall()
    ui.setupUi(formInstall)
    formInstall.show()
    sys.exit(app.exec_())
