# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1136, 685)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_top.setStyleSheet("background-color: rgb(3, 127, 140);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_btn_menu = QtWidgets.QFrame(self.frame_top)
        self.frame_btn_menu.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_btn_menu.setMaximumSize(QtCore.QSize(100, 35))
        self.frame_btn_menu.setStyleSheet("background-color: rgb(3, 127, 140);")
        self.frame_btn_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_menu.setObjectName("frame_btn_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_btn_menu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_menu = QtWidgets.QPushButton(self.frame_btn_menu)
        self.btn_menu.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_menu.setMaximumSize(QtCore.QSize(290, 35))
        self.btn_menu.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0367A6;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(32, 32))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_4.addWidget(self.btn_menu)
        self.horizontalLayout_2.addWidget(self.frame_btn_menu)
        self.frame_3 = QtWidgets.QFrame(self.frame_top)
        self.frame_3.setStyleSheet("background-color: rgb(3, 127, 140);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_top)
        self.fram_bot = QtWidgets.QFrame(self.centralwidget)
        self.fram_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fram_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fram_bot.setObjectName("fram_bot")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fram_bot)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_side = QtWidgets.QFrame(self.fram_bot)
        self.frame_side.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_side.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_side.setStyleSheet("background-color: #FFF;\n"
"border: 2px solid;\n"
"border-left: none;\n"
"border-top: none;\n"
"border-bottom:none;\n"
"border-right-color: rgb(3, 127, 140);")
        self.frame_side.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_side.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_side.setObjectName("frame_side")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_side)
        self.verticalLayout_2.setContentsMargins(5, 5, 10, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_coletar = QtWidgets.QPushButton(self.frame_side)
        self.btn_coletar.setMinimumSize(QtCore.QSize(280, 45))
        self.btn_coletar.setMaximumSize(QtCore.QSize(280, 45))
        self.btn_coletar.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0367A6;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_coletar.setObjectName("btn_coletar")
        self.verticalLayout_2.addWidget(self.btn_coletar)
        self.btn_visPossibilidades = QtWidgets.QPushButton(self.frame_side)
        self.btn_visPossibilidades.setMinimumSize(QtCore.QSize(280, 45))
        self.btn_visPossibilidades.setMaximumSize(QtCore.QSize(280, 45))
        self.btn_visPossibilidades.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0367A6;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_visPossibilidades.setObjectName("btn_visPossibilidades")
        self.verticalLayout_2.addWidget(self.btn_visPossibilidades)
        self.btn_visJogos = QtWidgets.QPushButton(self.frame_side)
        self.btn_visJogos.setMinimumSize(QtCore.QSize(280, 45))
        self.btn_visJogos.setMaximumSize(QtCore.QSize(280, 45))
        self.btn_visJogos.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0367A6;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_visJogos.setObjectName("btn_visJogos")
        self.verticalLayout_2.addWidget(self.btn_visJogos)
        self.btn_simular = QtWidgets.QPushButton(self.frame_side)
        self.btn_simular.setMinimumSize(QtCore.QSize(280, 45))
        self.btn_simular.setMaximumSize(QtCore.QSize(280, 45))
        self.btn_simular.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0367A6;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.btn_simular.setObjectName("btn_simular")
        self.verticalLayout_2.addWidget(self.btn_simular)
        spacerItem = QtWidgets.QSpacerItem(20, 383, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame_side)
        self.pushButton.setMinimumSize(QtCore.QSize(280, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(280, 35))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #0367A6;\n"
"    border-radius: 12px;\n"
"    border-bottom-color: rgb(4, 35, 38);\n"
"    border-right-color:  rgb(4, 35, 38);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: insetset;\n"
"    border-width: 2px;\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(3, 127, 140);\n"
"    border-radius: 8px;\n"
"    border-top-color: rgb(4, 35, 38);\n"
"    border-left-color:  rgb(4, 35, 38);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_side)
        self.frame_content = QtWidgets.QFrame(self.fram_bot)
        self.frame_content.setStyleSheet("background-color: #fff;")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_content)
        self.frame_2.setStyleSheet("background-color: #fff;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pages = QtWidgets.QStackedWidget(self.frame_2)
        self.pages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pages.setAutoFillBackground(False)
        self.pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pages.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pages.setLineWidth(1)
        self.pages.setObjectName("pages")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.pages.addWidget(self.page_home)
        self.page_possibilities = QtWidgets.QWidget()
        self.page_possibilities.setMouseTracking(False)
        self.page_possibilities.setTabletTracking(False)
        self.page_possibilities.setObjectName("page_possibilities")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_possibilities)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.page_possibilities)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_options = QtWidgets.QFrame(self.frame)
        self.frame_options.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_options.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_options.setStyleSheet("background-color: rgb(3, 127, 140);")
        self.frame_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_options.setLineWidth(1)
        self.frame_options.setObjectName("frame_options")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_options)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rb_DuplaChance = QtWidgets.QRadioButton(self.frame_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_DuplaChance.sizePolicy().hasHeightForWidth())
        self.rb_DuplaChance.setSizePolicy(sizePolicy)
        self.rb_DuplaChance.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_DuplaChance.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_DuplaChance.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_DuplaChance.setObjectName("rb_DuplaChance")
        self.horizontalLayout_6.addWidget(self.rb_DuplaChance)
        self.rb_matchOdds = QtWidgets.QRadioButton(self.frame_options)
        self.rb_matchOdds.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_matchOdds.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_matchOdds.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_matchOdds.setObjectName("rb_matchOdds")
        self.horizontalLayout_6.addWidget(self.rb_matchOdds)
        self.rb_ambosMarcam = QtWidgets.QRadioButton(self.frame_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_ambosMarcam.sizePolicy().hasHeightForWidth())
        self.rb_ambosMarcam.setSizePolicy(sizePolicy)
        self.rb_ambosMarcam.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_ambosMarcam.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_ambosMarcam.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_ambosMarcam.setObjectName("rb_ambosMarcam")
        self.horizontalLayout_6.addWidget(self.rb_ambosMarcam)
        self.rb_totalGols = QtWidgets.QRadioButton(self.frame_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_totalGols.sizePolicy().hasHeightForWidth())
        self.rb_totalGols.setSizePolicy(sizePolicy)
        self.rb_totalGols.setMinimumSize(QtCore.QSize(220, 20))
        self.rb_totalGols.setMaximumSize(QtCore.QSize(220, 20))
        self.rb_totalGols.setStyleSheet("\n"
"QRadioButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:pressed{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.rb_totalGols.setChecked(True)
        self.rb_totalGols.setAutoRepeat(True)
        self.rb_totalGols.setObjectName("rb_totalGols")
        self.horizontalLayout_6.addWidget(self.rb_totalGols)
        self.verticalLayout_5.addWidget(self.frame_options)
        self.frame_tb = QtWidgets.QFrame(self.frame)
        self.frame_tb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tb.setObjectName("frame_tb")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_tb)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tb_view = QtWidgets.QTableWidget(self.frame_tb)
        self.tb_view.setToolTipDuration(-3)
        self.tb_view.setObjectName("tb_view")
        self.tb_view.setColumnCount(41)
        self.tb_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_view.setHorizontalHeaderItem(40, item)
        self.verticalLayout_6.addWidget(self.tb_view)
        self.verticalLayout_5.addWidget(self.frame_tb)
        self.horizontalLayout_5.addWidget(self.frame)
        self.pages.addWidget(self.page_possibilities)
        self.horizontalLayout_3.addWidget(self.pages)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_commom = QtWidgets.QFrame(self.frame_content)
        self.frame_commom.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_commom.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_commom.setStyleSheet("background-color: rgb(3, 127, 140);\n"
"border-radius: 5px;\n"
"")
        self.frame_commom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_commom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_commom.setObjectName("frame_commom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_commom)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_commom)
        self.label_2.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame_commom)
        self.horizontalLayout.addWidget(self.frame_content)
        self.verticalLayout.addWidget(self.fram_bot)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Modulo Principal"))
        self.btn_menu.setText(_translate("Main", "Menu"))
        self.btn_coletar.setText(_translate("Main", "Coletar Dados"))
        self.btn_visPossibilidades.setText(_translate("Main", " Possibilidades"))
        self.btn_visJogos.setText(_translate("Main", "Visualizar Jogos"))
        self.btn_simular.setText(_translate("Main", "Simular Aposta"))
        self.pushButton.setText(_translate("Main", "Sobre"))
        self.rb_DuplaChance.setText(_translate("Main", "Dupla Chance"))
        self.rb_matchOdds.setText(_translate("Main", "Match Odds"))
        self.rb_ambosMarcam.setText(_translate("Main", "Ambos Marcam"))
        self.rb_totalGols.setText(_translate("Main", "Total de Gols"))
        item = self.tb_view.horizontalHeaderItem(0)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(1)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(2)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(3)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(4)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(5)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(6)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(7)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(8)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(9)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(10)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(11)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(12)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(13)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(14)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(15)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(16)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(17)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(18)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(19)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(20)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(21)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(22)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(23)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(24)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(25)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(26)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(27)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(28)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(29)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(30)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(31)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(32)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(33)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(34)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(35)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(36)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(37)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(38)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(39)
        item.setText(_translate("Main", "New Column"))
        item = self.tb_view.horizontalHeaderItem(40)
        item.setText(_translate("Main", "New Column"))
        self.label_2.setText(_translate("Main", "Todos os direitos reservados ©  MaTTecnologia Aplicada 2022"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
